# Generated by Django 2.2.4 on 2019-10-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_price',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
