# Generated by Django 2.2.4 on 2019-10-25 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textileapp', '0008_auto_20191015_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buynow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('apartment', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('postcode', models.IntegerField(max_length=6)),
                ('phone', models.IntegerField(max_length=12)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
