# Generated by Django 2.2.4 on 2019-10-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0009_buynow'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='buynow',
            name='firstname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='buynow',
            name='lastname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='buynow',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='buynow',
            name='postcode',
            field=models.IntegerField(default=None),
        ),
    ]
