# Generated by Django 2.2.4 on 2019-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0010_auto_20191025_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
